### ISSUE TITLE
404 Error on /sign-in Route After Cloning and Running the Project

### ISSUE THREAD

**Issue by SeifBh** [horizon-ui/shadcn-nextjs-boilerplate#1]
Hello,
When I run the project, I encounter the following issues:

- The web front shows a 404 Not Found error.
- In the browser console, the error message is:
```bash
npm run dev

> shadcn-nextjs-boilerplate@2.1.1 dev
> next dev

  ▲ Next.js 14.2.14
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Starting...
 ✓ Ready in 3.3s
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 1407ms (143 modules)
 ○ Compiling / ...
 ✓ Compiled / in 8.4s (889 modules)
 GET / 307 in 9225ms
 ✓ Compiled in 973ms (381 modules)
 ○ Compiling /_not-found ...
 ✓ Compiled /_not-found in 6.6s (878 modules)
 GET /sign-in 404 in 6918ms
```
I’ve ensured that all the steps were followed correctly, but I’m unsure what might be causing this issue.

Could you please advise on how to resolve this?

Thank you!
![image](https://github.com/user-attachments/assets/8f2040f5-ffeb-4bf9-99f9-e06de046eb95)

**Comment by simmmpleweb** [comment]
Fixed!
