### ISSUE TITLE
OpenAI API Key

### ISSUE THREAD

**Issue by cgberlin** [horizon-ui/shadcn-nextjs-boilerplate#2]
You have a public/hardcoded OpenAI API key in your repo, hopefully you've killed it off by now, but probably worth removing the reference. 

https://github.com/horizon-ui/shadcn-nextjs-boilerplate/blob/main/app/api/s3-upload/route.js

**Comment by simmmpleweb** [comment]
Hello, @cgberlin! Indeed, that key is not active, but we replaced it with `process.env.NEXT_PUBLIC_OPENAI_API_KEY` as it should have been in the first place. Thank you for noticing!
